---
#-----------------------------------------------------------------
# DEEPFLOW MYSQL
#-----------------------------------------------------------------
deepflow_mysql_enabled: true

deepflow_mysql_stack_dir: /opt/deepflow-mysql
deepflow_mysql_env_file: /etc/default/deepflow-mysql
deepflow_mysql_compose_file: "{{ deepflow_mysql_stack_dir }}/docker-compose.yml"
deepflow_mysql_data: /data/deepflow/mysql

deepflow_mysql_image: mysql:8.4
deepflow_mysql_port: 13306

deepflow_mysql_root_password: DeepFlow.Root.ChangeMe
deepflow_mysql_user: deepflow
deepflow_mysql_password: DeepFlow.MySQL.ChangeMe
deepflow_mysql_database: deepflow
