#!/usr/bin/env ansible-playbook
---
#==============================================================#
# File      :   deepflow.yml
# Desc      :   deploy deepflow server stack
# Ctime     :   2026-02-04
# Mtime     :   2026-02-04
# Path      :   deepflow.yml
# License   :   Apache-2.0 @ https://pigsty.io/docs/about/license/
#==============================================================#

- name: DEEPFLOW SERVER
  become: true
  hosts: all
  gather_facts: no

  roles:
    - { role: node_id         , tags: node-id,        when: deepflow_enabled | default(true) | bool }
    - { role: deepflow_server , tags: deepflow_server, when: deepflow_enabled | default(true) | bool }

# Usage:
# 1. Define deepflow group in pigsty.yml
# 2. Ensure docker is installed: ./docker.yml
# 3. Run ./deepflow.yml -l <deepflow_group>
